{% set version = "2.5.1" %}

package:
  name: neovim-remote
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/neovim-remote/neovim-remote-{{ version }}.tar.gz
  sha256: 4b3cc35463544c5747c895c52a0343cfdbba15d307647d7f57f1cce0c6a27d02

build:
  entry_points:
    - nvr = nvr.nvr:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - psutil
    - pynvim
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - nvr
  commands:
    - pip check
    - nvr --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mhinz/neovim-remote
  summary: Control nvim processes using "nvr" commandline tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
